# Generated by Django 5.0 on 2023-12-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='deleted',
            new_name='is_deleted',
        ),
    ]
