# Generated by Django 5.0 on 2023-12-26 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='linkedUser',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='linkedAuthor',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='linkedPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linkedComments', to='app.post'),
        ),
    ]
