# Generated by Django 5.0 on 2023-12-26 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_user_comment_linkeduser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='commentText',
        ),
    ]
