# Generated by Django 5.0 on 2023-12-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_text_comment_commenttext'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='familyTree',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
